
// This file has been generated by the GUI designer. Do not modify.

public partial class ConfigKey
{
	private global::Gtk.Table tblConfigWidgets;
	
	private global::Gtk.ToggleButton btnEnabled;
	
	private global::Gtk.Label lblKey;
	
	private global::Gtk.Button btnCancel;
	
	private global::Gtk.Button btnAccept;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget ConfigKey
		this.Name = "ConfigKey";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Internal child ConfigKey.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog1_VBox";
		w1.BorderWidth = ((uint)(2));
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.tblConfigWidgets = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.tblConfigWidgets.Name = "tblConfigWidgets";
		this.tblConfigWidgets.RowSpacing = ((uint)(6));
		this.tblConfigWidgets.ColumnSpacing = ((uint)(6));
		// Container child tblConfigWidgets.Gtk.Table+TableChild
		this.btnEnabled = new global::Gtk.ToggleButton ();
		this.btnEnabled.CanFocus = true;
		this.btnEnabled.Name = "btnEnabled";
		this.btnEnabled.UseUnderline = true;
		this.btnEnabled.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.tblConfigWidgets.Add (this.btnEnabled);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblConfigWidgets [this.btnEnabled]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblConfigWidgets.Gtk.Table+TableChild
		this.lblKey = new global::Gtk.Label ();
		this.lblKey.Name = "lblKey";
		this.lblKey.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.tblConfigWidgets.Add (this.lblKey);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblConfigWidgets [this.lblKey]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		w1.Add (this.tblConfigWidgets);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.tblConfigWidgets]));
		w4.Position = 0;
		// Internal child ConfigKey.ActionArea
		global::Gtk.HButtonBox w5 = this.ActionArea;
		w5.Name = "dialog1_ActionArea";
		w5.Spacing = 10;
		w5.BorderWidth = ((uint)(5));
		w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.CanDefault = true;
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseStock = true;
		this.btnCancel.UseUnderline = true;
		this.btnCancel.Label = "gtk-cancel";
		this.AddActionWidget (this.btnCancel, -6);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.btnCancel]));
		w6.Expand = false;
		w6.Fill = false;
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.btnAccept = new global::Gtk.Button ();
		this.btnAccept.CanDefault = true;
		this.btnAccept.CanFocus = true;
		this.btnAccept.Name = "btnAccept";
		this.btnAccept.UseUnderline = true;
		this.btnAccept.Label = global::Mono.Unix.Catalog.GetString ("_Accept");
		global::Gtk.Image w7 = new global::Gtk.Image ();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.btnAccept.Image = w7;
		this.AddActionWidget (this.btnAccept, -3);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.btnAccept]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.btnCancel.Clicked += new global::System.EventHandler (this.onCancel);
		this.btnAccept.Clicked += new global::System.EventHandler (this.onAccept);
	}
}
