
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button btnG1;
	
	private global::Gtk.Button btnG10;
	
	private global::Gtk.Button btnG11;
	
	private global::Gtk.Button btnG12;
	
	private global::Gtk.Button btnG13;
	
	private global::Gtk.Button btnG14;
	
	private global::Gtk.Button btnG15;
	
	private global::Gtk.Button btnG16;
	
	private global::Gtk.Button btnG17;
	
	private global::Gtk.Button btnG18;
	
	private global::Gtk.Button btnG2;
	
	private global::Gtk.Button btnG3;
	
	private global::Gtk.Button btnG4;
	
	private global::Gtk.Button btnG5;
	
	private global::Gtk.Button btnG6;
	
	private global::Gtk.Button btnG7;
	
	private global::Gtk.Button btnG8;
	
	private global::Gtk.Button btnG9;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Corsair K95 Linux configurator by Radic");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.btnG1 = new global::Gtk.Button ();
		this.btnG1.CanFocus = true;
		this.btnG1.Name = "btnG1";
		this.btnG1.UseUnderline = true;
		this.btnG1.Label = global::Mono.Unix.Catalog.GetString ("G1");
		this.table1.Add (this.btnG1);
		// Container child table1.Gtk.Table+TableChild
		this.btnG10 = new global::Gtk.Button ();
		this.btnG10.CanFocus = true;
		this.btnG10.Name = "btnG10";
		this.btnG10.UseUnderline = true;
		this.btnG10.Label = global::Mono.Unix.Catalog.GetString ("G10");
		this.table1.Add (this.btnG10);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG10]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btnG11 = new global::Gtk.Button ();
		this.btnG11.CanFocus = true;
		this.btnG11.Name = "btnG11";
		this.btnG11.UseUnderline = true;
		this.btnG11.Label = global::Mono.Unix.Catalog.GetString ("G11");
		this.table1.Add (this.btnG11);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG11]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG12 = new global::Gtk.Button ();
		this.btnG12.CanFocus = true;
		this.btnG12.Name = "btnG12";
		this.btnG12.UseUnderline = true;
		this.btnG12.Label = global::Mono.Unix.Catalog.GetString ("G12");
		this.table1.Add (this.btnG12);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG12]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btnG13 = new global::Gtk.Button ();
		this.btnG13.CanFocus = true;
		this.btnG13.Name = "btnG13";
		this.btnG13.UseUnderline = true;
		this.btnG13.Label = global::Mono.Unix.Catalog.GetString ("G13");
		this.table1.Add (this.btnG13);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG13]));
		w7.TopAttach = ((uint)(4));
		w7.BottomAttach = ((uint)(5));
		// Container child table1.Gtk.Table+TableChild
		this.btnG14 = new global::Gtk.Button ();
		this.btnG14.CanFocus = true;
		this.btnG14.Name = "btnG14";
		this.btnG14.UseUnderline = true;
		this.btnG14.Label = global::Mono.Unix.Catalog.GetString ("G14");
		this.table1.Add (this.btnG14);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG14]));
		w8.TopAttach = ((uint)(4));
		w8.BottomAttach = ((uint)(5));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG15 = new global::Gtk.Button ();
		this.btnG15.CanFocus = true;
		this.btnG15.Name = "btnG15";
		this.btnG15.UseUnderline = true;
		this.btnG15.Label = global::Mono.Unix.Catalog.GetString ("G15");
		this.table1.Add (this.btnG15);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG15]));
		w9.TopAttach = ((uint)(4));
		w9.BottomAttach = ((uint)(5));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btnG16 = new global::Gtk.Button ();
		this.btnG16.CanFocus = true;
		this.btnG16.Name = "btnG16";
		this.btnG16.UseUnderline = true;
		this.btnG16.Label = global::Mono.Unix.Catalog.GetString ("G16");
		this.table1.Add (this.btnG16);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG16]));
		w10.TopAttach = ((uint)(5));
		w10.BottomAttach = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.btnG17 = new global::Gtk.Button ();
		this.btnG17.CanFocus = true;
		this.btnG17.Name = "btnG17";
		this.btnG17.UseUnderline = true;
		this.btnG17.Label = global::Mono.Unix.Catalog.GetString ("G17");
		this.table1.Add (this.btnG17);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG17]));
		w11.TopAttach = ((uint)(5));
		w11.BottomAttach = ((uint)(6));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG18 = new global::Gtk.Button ();
		this.btnG18.CanFocus = true;
		this.btnG18.Name = "btnG18";
		this.btnG18.UseUnderline = true;
		this.btnG18.Label = global::Mono.Unix.Catalog.GetString ("G18");
		this.table1.Add (this.btnG18);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG18]));
		w12.TopAttach = ((uint)(5));
		w12.BottomAttach = ((uint)(6));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btnG2 = new global::Gtk.Button ();
		this.btnG2.CanFocus = true;
		this.btnG2.Name = "btnG2";
		this.btnG2.UseUnderline = true;
		this.btnG2.Label = global::Mono.Unix.Catalog.GetString ("G2");
		this.table1.Add (this.btnG2);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG2]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG3 = new global::Gtk.Button ();
		this.btnG3.CanFocus = true;
		this.btnG3.Name = "btnG3";
		this.btnG3.UseUnderline = true;
		this.btnG3.Label = global::Mono.Unix.Catalog.GetString ("G3");
		this.table1.Add (this.btnG3);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG3]));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btnG4 = new global::Gtk.Button ();
		this.btnG4.CanFocus = true;
		this.btnG4.Name = "btnG4";
		this.btnG4.UseUnderline = true;
		this.btnG4.Label = global::Mono.Unix.Catalog.GetString ("G4");
		this.table1.Add (this.btnG4);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG4]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG5 = new global::Gtk.Button ();
		this.btnG5.CanFocus = true;
		this.btnG5.Name = "btnG5";
		this.btnG5.UseUnderline = true;
		this.btnG5.Label = global::Mono.Unix.Catalog.GetString ("G5");
		this.table1.Add (this.btnG5);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG5]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG6 = new global::Gtk.Button ();
		this.btnG6.CanFocus = true;
		this.btnG6.Name = "btnG6";
		this.btnG6.UseUnderline = true;
		this.btnG6.Label = global::Mono.Unix.Catalog.GetString ("G6");
		this.table1.Add (this.btnG6);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG6]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btnG7 = new global::Gtk.Button ();
		this.btnG7.CanFocus = true;
		this.btnG7.Name = "btnG7";
		this.btnG7.UseUnderline = true;
		this.btnG7.Label = global::Mono.Unix.Catalog.GetString ("G7");
		this.table1.Add (this.btnG7);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG7]));
		w18.TopAttach = ((uint)(2));
		w18.BottomAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btnG8 = new global::Gtk.Button ();
		this.btnG8.CanFocus = true;
		this.btnG8.Name = "btnG8";
		this.btnG8.UseUnderline = true;
		this.btnG8.Label = global::Mono.Unix.Catalog.GetString ("G8");
		this.table1.Add (this.btnG8);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG8]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btnG9 = new global::Gtk.Button ();
		this.btnG9.CanFocus = true;
		this.btnG9.Name = "btnG9";
		this.btnG9.UseUnderline = true;
		this.btnG9.Label = global::Mono.Unix.Catalog.GetString ("G9");
		this.table1.Add (this.btnG9);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnG9]));
		w20.TopAttach = ((uint)(2));
		w20.BottomAttach = ((uint)(3));
		w20.LeftAttach = ((uint)(2));
		w20.RightAttach = ((uint)(3));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 472;
		this.DefaultHeight = 251;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnG1.Clicked += new global::System.EventHandler (this.btnG1Click);
	}
}
